# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-source
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.source.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f874706ac071274b50e2a134f0b4f3b9ca7d04895bc1f7d2299df23d15abce75_sk
      - FABRIC_CA_SERVER_PORT=6054
    ports:
      - "6054:6054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.source.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f874706ac071274b50e2a134f0b4f3b9ca7d04895bc1f7d2299df23d15abce75_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/source.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSource
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-process
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.process.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/841c28f1ecfcb89713b22a25a5c301595d904ca3b5266e441ef15746d50c82a2_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.process.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/841c28f1ecfcb89713b22a25a5c301595d904ca3b5266e441ef15746d50c82a2_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/process.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerProcess
    networks:
      - byfn

  ca2:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-logistics
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.logistics.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b49134acb840233cc6886445ca258cb1ceeff8c50ad30e46a626c18ec376c083_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.logistics.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b49134acb840233cc6886445ca258cb1ceeff8c50ad30e46a626c18ec376c083_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/logistics.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerLogistics
    networks:
      - byfn

  ca3:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-sales
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.sales.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/13f0d04329a93756e45768075b4fa37325f34399cbe89b0086974ef7d83d5bb0_sk
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.sales.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/13f0d04329a93756e45768075b4fa37325f34399cbe89b0086974ef7d83d5bb0_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/sales.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSales
    networks:
      - byfn
