# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.source.example.com:
  peer0.process.example.com:
  peer0.logistics.example.com:
  peer0.sales.example.com:

networks:
  byfn:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - byfn

  peer0.source.example.com:
    container_name: peer0.source.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.source.example.com
    networks:
      - byfn

  peer0.process.example.com:
    container_name: peer0.process.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.process.example.com
    networks:
      - byfn

  peer0.logistics.example.com:
    container_name: peer0.logistics.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.logistics.example.com
    networks:
      - byfn

  peer0.sales.example.com:
    container_name: peer0.sales.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.sales.example.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=firstchannel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.source.example.com:6051
      - CORE_PEER_LOCALMSPID=SourceMSP
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/source.example.com/peers/peer0.source.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/source.example.com/peers/peer0.source.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/source.example.com/peers/peer0.source.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/source.example.com/users/Admin@source.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.source.example.com
      - peer0.process.example.com
      - peer0.logistics.example.com
      - peer0.sales.example.com
    networks:
      - byfn
